#!/bin/sh -e

# Ensure we're in the root ~/.vim directory
cd "$( dirname "$0" )/.."
ROOT=`pwd`

# Fetch and checkout the submodule revision
# specified by the parent git repository.
echo "Fetching vim plugins"
echo "(in `pwd`)"
git submodule init
git submodule update

if [ ! "x$1" = "x--fetch-only" ]; then
    # Upgrades vim plugins to the latest commit
    # available in their respective origin/master
    # branches
    echo "Upgrading vim plugins"
    echo "(in `pwd`)"
    git submodule foreach git pull --ff-only origin master
fi

# Build Command-T
cd $ROOT/bundle/command-t
echo "Building Command-T"
rake make
